### ISSUE TITLE
获得作者作品的 API 失效

### ISSUE THREAD

**Issue by sanddudu** [bebound/Pixiv#1]
http://spapi.pixiv.net/iphone/member_illust.php 这个地址提示 404

**Comment by bebound** [comment]
Pixiv改变了API
新版本地址为https://public-api.secure.pixiv.net
最近没有时间更新

**Comment by sanddudu** [comment]
好像直接改地址不行，返回的还是 404
接口的方法有修改吗

**Comment by bebound** [comment]
不行 整个都换了

你可以看看这个项目 https://github.com/upbit/pixivpy

—
通过 Mailbox 发送

**Comment by sanddudu** [comment]
谢谢

**Comment by bebound** [comment]
已修复
