### ISSUE TITLE
Can't find crypto and access pxiv.py file

### ISSUE THREAD

**Issue by AbdulrahmanHadz** [bebound/Pixiv#12]
Is what i'm doing right and is that how you access the pixiv python file?

**Comment by sanddudu** [comment]
Please install all dependencies first.

**Comment by AbdulrahmanHadz** [comment]
how do i do that?

**Comment by bebound** [comment]
pip install -r requirements.txt

**Comment by AbdulrahmanHadz** [comment]
I get this error:

**Comment by bebound** [comment]
Compiling package on Windows is really painful.
If you're using Python3.5, someone has made a wheel. Following the instructions [here](https://github.com/sfbahr/PyCrypto-Wheels) to install `pycrypto`, then install the rest packages by the  former command.
If not, you may find solution on google or stackoverflow, good luck.
