### ISSUE TITLE
画师名出现系统不允许的特殊字符时无法保存

### ISSUE THREAD

**Issue by ghost** [bebound/Pixiv#15]
已自行尝试修改，修改pixiv.py中user_name = illustration.user_name.replace('*','_').replace(';','_')这种方法即可实现

**Comment by bebound** [comment]
这两行应该把特殊字符过滤掉了吧
有没有出错的例子？
https://github.com/bebound/pixiv/blob/master/pixiv.py#L176-L177

**Comment by ghost** [comment]
这个版本应该是没问题的，上一个版本的事了...不过考虑程序稳定性，在Windows环境运行遇到极端情况画师名为LPT加数字 COM加数字也是会导致程序直接崩溃。

**Comment by bebound** [comment]
按道理不应该出问题的，我先把issue关了，有问题你再重新打开好了。
