### ISSUE TITLE
GIFs download bad 

### ISSUE THREAD

**Issue by fluffyloopy** [bebound/Pixiv#16]
GIFs get downloaded frame by frame instead of as a whole gif. why?

**Comment by bebound** [comment]
They're frames, although in Pixiv they looks like gif. You can convert them to gif if you like.

**Comment by fluffyloopy** [comment]
is there any way to implement something like [this](https://github.com/altbdoor/py-ugoira/blob/master/py_ugoira.py) to it so the final version is a downloaded gif instead of frames?

**Comment by bebound** [comment]
I can do this, but I think it's not the responsibility for this repo to do this. (Users also need to install FFmpeg)
You can write a shell script to achieve this.

PS: I personally don't like gif format, it's big and poor quality.

**Comment by fluffyloopy** [comment]
That's fair, which format would you suggest then?
