### ISSUE TITLE
I can not log in

### ISSUE THREAD

**Issue by Coro365** [bebound/Pixiv#17]
I've used it for about two years, but I can't log in since yesterday(2019.09.02).
`Login failed:('[ERROR] connection failed!', 400)`
Is this due to my account or IP address?
Thank you for the wonderful software.

**Comment by bebound** [comment]
Thanks for the feedback, this should be fixed by the latest commit.

**Comment by Coro365** [comment]
Thank you!!

**Comment by fluffyloopy** [comment]
It's happening again
