### ISSUE TITLE
Idea: Graph-based user recommendation

### ISSUE THREAD

**Issue by DonaldTsang** [bebound/Pixiv#19]
If I were to give you 300 artists of similar themes, is it possible to find other related artists that produces such themes (assume that we are going 3 levels deep, that means A liking B liking C liking D means all of them are related)?

**Comment by bebound** [comment]
That's what recommendation system do. My scripts can't achieve this without user data.

You may use follow and favorite information to make simple recommendation system like user-based CF and item-based CF. But more powerful recommendation system like [this](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/45530.pdf) can only be implemented by Pixiv.

**Comment by DonaldTsang** [comment]
So some of my idea is to use this repo and add a Recommendation System based on it,
some libraries have a long list of recommendations like:
- https://github.com/guoguibing/librec
- https://github.com/zhenghaoz/gorse

but I would like to see some in Python as well like https://github.com/benfred/implicit 
Some basic principles though: no neural networks (since it is computationally intensive)
The goal would would be to scrape your favorite artists' "collections" for preferences,
and then use their preferences for CF similar artists with the same themes or properties.

And I would like to put some co-references here:
- https://github.com/chenjiandongx/pixiv
- https://github.com/tsubasa/pixiv.py
- https://github.com/Akaisorani/pixiv-crawler
