### ISSUE TITLE
Update exist not working

### ISSUE THREAD

**Issue by fluffyloopy** [bebound/Pixiv#23]
Returns "code" instead of updating 
![Screenshot_20200919-152747_Termux](https://user-images.githubusercontent.com/36381994/93665031-bbb83b00-fa8c-11ea-9809-e66be5638f10.jpg)

**Comment by bebound** [comment]
I can't reproduce this error.

Could you please check your internet connection is correct, make sure you've logged in and using the latest code version.

**Comment by fluffyloopy** [comment]
It works now for some reason. Might be a cause of slow wifi
