### ISSUE TITLE
login failed 400

### ISSUE THREAD

**Issue by ghost** [bebound/Pixiv#24]
![1](https://user-images.githubusercontent.com/16064020/101197979-21888c00-36a6-11eb-90e8-8e797968fb6e.png)
![2](https://user-images.githubusercontent.com/16064020/101197981-22212280-36a6-11eb-9732-9978e088fa07.png)
Screenshoot.
May be api changed. try to use different network and not work too.
the first image is running with pc,second image is running with US server and force it prints the request content.
I also try to use another account and different network,none work.

**Comment by bebound** [comment]
Sorry, I can't reproduce it. Can you login on website?

**Comment by ghost** [comment]
> Sorry, I can't reproduce it. Can you login on website?

Yes. That account and IP address are not blocked by pixiv. I try it for 10 servers and none work. I try it with some home ADSL which located Japan but also returns the same error.

**Comment by ghost** [comment]
solved. The pixiv update the security settings. I can login web but it shows me "do you want to change your password?" and I ignore it.so I can login web but cannot login into API. When I reset the password, It works. It just likes force password update. Thanks for your patient trying and this issues has been solved.
the error code are decoded with "{"has_error":true,"errors":{"system":{"message":"103:pixiv ID、またはメールアドレス、パスワードが正しいかチェックしてください。","code":1508}},"error":"invalid_grant"}"
