### ISSUE TITLE
Artist [number] Fetch Failed

### ISSUE THREAD

**Issue by JocPro** [bebound/Pixiv#25]
While trying to download an user's illustrations for the first time, it gave me this error:

```
################### download by user id ####################

Input the artist's id:(separate with space)*******
Artists *******
Artist ******* Fetch Failed
There is no new illustration need to download

############### download by user id finished ###############
```

Every subsequent try gave me the same error. Every other author works fine.
I suspect there may be an overflow somewhere, as the artist has over 17000 pieces of artwork with over 40000 image files in total,

His userid is 6900862

**Comment by bebound** [comment]
Thank you. This should be fixed now.
