### ISSUE TITLE
Login Fail 400 again

### ISSUE THREAD

**Issue by ghost** [bebound/Pixiv#26]
I'm sorry to bothering the author again but I can't resolve it.
not the same as #24 ,I try to change my password firstly, and I can login Pixiv's webpage with out any errors and warning, but now downloader returns me this error:

![0](https://user-images.githubusercontent.com/16064020/107354421-79fa6080-6b11-11eb-9b3c-0be54e7781cd.png)

This error is printed by this self added command which located in api.py:
![3](https://user-images.githubusercontent.com/16064020/107354592-b1690d00-6b11-11eb-8205-9c569ec52195.png)

I go to the pixivpy project and see this:https://github.com/upbit/pixivpy/issues/158
It seems that pixiv changed api auth method.

Thanks a lot.

**Comment by bebound** [comment]
Thanks for you report, wait for upstream to fix this...

**Comment by bebound** [comment]
I've update the code to use OAuth login. Check https://gist.github.com/ZipFile/c9ebedb224406f4f11845ab700124362 to get login token.
