### ISSUE TITLE
关于动画的获取方式

### ISSUE THREAD

**Issue by sanddudu** [bebound/Pixiv#9]
之前好像是直接把每一帧都下载下来（导致目录里可能有点乱），现在是只载第一张（目测）
网页版好像是下载一个 zip 文件（之前迅雷捕获链接之后发现的），请问目前的 api 可以改成这种模式吗（相对于直接下载每一帧来说，目录比较整洁）

**Comment by bebound** [comment]
应该是要下载每一帧的图片的 我测试下
出于方便浏览的考虑 没有重新打包的打算

**Comment by DaddyTrap** [comment]
@bebound 
鄙人看了一下[这个wiki](https://github.com/upbit/pixivpy/wiki/Sniffer-for-Ugoira#papi-works)和代码

嗯……如果没理解错的话，代码中是通过image_urls来确定下载的文件的，而新的api返回的动图的image_urls应该确实只是动图的一个预览。而 @sanddudu 提到的zip是写在api返回的metadata里面的

如果可以的话，我想最好可以自动合成gif，那就更方便了
(或许我可以加入这个功能？然而发现按现在的model结构，改起来似乎有些难……)

**Comment by bebound** [comment]
`extract_common_information`里添加一下`"type": "ugoira" `的特殊处理就好了
要是动图的地址都是这种形式 改下`page_count`就能自动下完所有图片了
·http://i3.pixiv.net/img-original/img/2016/12/24/09/08/39/60518582_ugoira0.jpg·

**Comment by DaddyTrap** [comment]
尝试发现确实可以
感谢！

**Comment by bebound** [comment]
@DaddyTrap 奇怪 为什么返回的原始json中没有`metadata`字段？

**Comment by DaddyTrap** [comment]
@bebound 是的……可能原本的根据user获取作品列表的API就是不返回metadata的……

我现在的做法是用获取单个图片信息的API来获取帧数，也就是ugoira的pagecount
